# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='deadlineTime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateField(),
        ),
    ]
