# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaas', '0002_auto_20171001_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='deadlineTime',
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='minimum_price',
            field=models.FloatField(),
        ),
    ]
