# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0005_auto_20171009_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='seller',
        ),
    ]
