# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0008_auto_20171009_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
