# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0010_auto_20171010_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 16, 39, 53, 349266)),
            preserve_default=False,
        ),
    ]
