# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaas', '0011_auto_20171012_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('W', 'Wining'), ('L', 'Losing')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='lifecycle',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Banned'), ('D', 'Due'), ('X', 'Adjudicated')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaas.Auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
