# Generated by Django 2.0.1 on 2018-01-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0013_auto_20171229_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
