# Generated by Django 2.0 on 2018-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0014_auction_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lock_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='lifecycle',
            field=models.CharField(choices=[('A', 'Active/Due'), ('B', 'Banned'), ('X', 'Adjudicated')], default='A', max_length=1),
        ),
    ]
