# Generated by Django 2.0.1 on 2018-01-21 00:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0015_auto_20180119_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
