# Generated by Django 2.0.1 on 2018-01-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0018_auto_20180121_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(default=None, max_length=24),
        ),
    ]
