# Generated by Django 2.0.1 on 2018-01-21 02:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0019_auto_20180121_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='minimum_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
