# Generated by Django 2.0.1 on 2018-01-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0022_auto_20180121_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(default=' ', max_length=24),
        ),
    ]
