# Generated by Django 2.0.1 on 2018-01-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaas', '0023_auto_20180121_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=24),
        ),
    ]
